export const blog_data = [
  {
    id: 1,
    title: "A Detailed Step-by-Step Guide to Manage Your Lifestyle",
    description: "Learn how to structure your day, build healthy habits, and achieve a balanced life with this comprehensive guide.",
    image: "/assets/blog1.jpg",
    date: Date.now(),
    category: "LifeStyle",
    author: "Alex Bennet",
    author_img: "/assets/profile_1.png",
  },
  {
    id: 2,
    title: "10 Daily Habits That Can Change Your Life",
    description: "Simple yet powerful daily habits that can transform your productivity, health, and overall well-being.",
    image: "/assets/blog2.jpg",
    date: Date.now(),
    category: "LifeStyle",
    author: "Sarah Jenkins",
     author_img: "/assets/profile_2.png",
  },
  {
    id: 3,
    title: "How to Launch Your First Startup Without Funding",
    description: "Discover lean startup principles and bootstrap your way to launching a successful business from scratch.",
    image: "/assets/blog3.jpg",
    date: Date.now(),
    category: "Startup",
    author: "John Doe",
    author_img: "/assets/profile_3.jpg",
  },
  {
    id: 4,
    title: "The Future of AI: What to Expect in 2025",
    description: "From generative models to autonomous systems — here’s how AI is shaping the future of industries.",
    image: "/assets/tech1.jpg",
    date: Date.now(),
    category: "Technology",
    author: "Priya Patel",
     author_img: "/assets/profile_4.png",
  },
  {
    id: 5,
    title: "Minimalist Living: A Guide to Simplicity",
    description: "Explore how simplifying your possessions and mindset can lead to a more intentional and fulfilling life.",
   image: "/assets/tech2.jpg",
    date: Date.now(),
    category: "LifeStyle",
    author: "Michael Clarke",
    author_img: "/assets/profile_5.jpg",
  },
  {
    id: 6,
    title: "Top 5 Tools Every Tech Entrepreneur Should Use",
    description: "From project management to marketing automation, these tools are essential for startup founders.",
    image: "/assets/tech3.jpg",
    date: Date.now(),
    category: "Startup",
    author: "Rachel Green",
     author_img: "/assets/profile_6.jpg",
  },
  {
    id: 7,
    title: "Building Scalable Apps with Serverless Architecture",
    description: "Learn how to design and deploy scalable applications using serverless platforms like AWS Lambda.",
    image: "/assets/tech4.jpg",
    date: Date.now(),
    category: "Technology",
    author: "David Lin",
    author_img: "/assets/profile_7.jpg",
  },
  {
    id: 8,
    title: "Work-Life Balance: Tips from Top Executives",
    description: "How successful leaders manage stress and stay productive without burning out.",
    image: "/assets/tech5.jpg",
    date: Date.now(),
    category: "LifeStyle",
    author: "Anna Johnson",
     author_img: "/assets/profile_8.png",
  },
  {
    id: 9,
    title: "Startup Funding: What Investors Look For",
    description: "Get inside the mind of a venture capitalist and learn how to pitch your startup effectively.",
   image: "/assets/tech6.jpg",
    date: Date.now(),
    category: "Startup",
    author: "Carlos Mendes",
   author_img: "/assets/profile_9.png",
  },
  {
    id: 10,
    title: "Quantum Computing: The Next Big Leap",
    description: "Explore how quantum computers could revolutionize fields like cryptography, logistics, and AI.",
    image: "/assets/startup1.jpg",
    date: Date.now(),
    category: "Technology",
    author: "Sophia Lee",
     author_img: "/assets/profile_10.jpg",
  },
  {
    id: 11,
    title: "Digital Detox: Reclaiming Time in a Hyperconnected World",
    description: "Strategies to unplug from screens, reduce digital overwhelm, and reconnect with real life.",
    image: "/assets/startup2.jpg",
    date: Date.now(),
    category: "LifeStyle",
    author: "Nina Walker",
     author_img: "/assets/profile_11.png",
  },
  {
    id: 12,
    title: "From Idea to MVP: A Startup’s Journey",
    description: "Follow the real-life steps and tools used by startups to bring an idea to life and market.",
    image: "/assets/startup3.jpg",
    date: Date.now(),
    category: "Startup",
    author: "Liam Scott",
    author_img: "/assets/profile_12.jpg",
  },
  {
    id: 13,
    title: "The Rise of Edge Computing",
    description: "Learn how edge computing reduces latency and transforms IoT, gaming, and autonomous tech.",
   image: "/assets/startup4.jpg",
    date: Date.now(),
    category: "Technology",
    author: "Meera Sharma",
    author_img: "/assets/profile_13.jpg",
  },
  {
    id: 14,
    title: "Mindfulness Techniques to Improve Focus",
    description: "Practical mindfulness exercises to sharpen attention and reduce anxiety in daily life.",
    image: "/assets/startup5.png",
    date: Date.now(),
    category: "LifeStyle",
    author: "Kevin Yates",
    author_img: "/assets/profile_14.jpg",
  },
  {
    id: 15,
    title: "Why Most Startups Fail — And How to Avoid It",
    description: "Understand common pitfalls in early-stage startups and how to build a sustainable company.",
    image: "/assets/startup6.png",
    date: Date.now(),
    category: "Startup",
    author: "Olivia Brooks",
     author_img: "/assets/profile_15.png",
  },
];
